#!/usr/bin/env python3
"""Generate ~/.config/starship.toml with Nerd Font glyphs injected via chr().

Hand-editing ~/.config/starship.toml drops the Private-Use-Area glyphs in most
editors, so change THIS file and re-run:  python3 ~/.config/starship-gen.py
Validate:  starship print-config 2>&1 | grep -iE 'warn|error'
"""

import os

# --- glyphs ----------------------------------------------------------------
HARD_R = chr(0xE0B0)  #  right-pointing filled triangle   left-bar end (points at cursor)
HARD_L = chr(0xE0B2)  #  left-pointing filled triangle     right-bar nose (points at cursor)
CHEV_R = chr(0xE0B1)  #  thin right chevron               left-bar soft divider
BRANCH = chr(0xE0A0)  #  git branch
CLOCK  = chr(0xF017)  #  clock         cmd_duration
NODE   = chr(0xE718)  #  node.js       nodejs
GO     = chr(0xE627)  #  go            golang
RUST   = chr(0xE7A8)  #  rust          rust
PY     = chr(0xE606)  #  python        python
AWS    = chr(0xE7AD)  #  aws           aws
KUBE   = "☸"      # ☸ dharma wheel (plain Unicode) kubernetes
FAIL   = "✘"     # ✘ heavy ballot X (plain Unicode) status

# --- palette -------------------------------------------------------------
L_HOST = "bg:#434C5E fg:#ECEFF4"
L_DIR  = "bg:#5E81AC fg:#ECEFF4"

# RIGHT bar: ONE flat slate bar. Every segment shares this background;
# segments are told apart by a coloured icon + coloured text, not by blocks.
BAR = "#3B4252"

TOML = f'''# ~/.config/starship.toml   (generated by ~/.config/starship-gen.py -- do not hand-edit)
#
# LEFT bar  = identity / location, ALWAYS shown, one seamless block-bar:
#     host {CHEV_R} user  {HARD_R}  directory {HARD_R}
#   The "{HARD_R}" between the blocks carries the previous block colour as fg
#   and the next as bg (seamless); the final "{HARD_R}" points at the cursor.
#
# RIGHT bar = transient / contextual status, shown only when relevant. ONE
#   flat slate bar (background {BAR}); segments share it and are told apart by
#   a coloured icon + coloured text. A literal "{HARD_L}" is pinned to the
#   front of right_format (same style as the left bar's "{HARD_R}" end) so the
#   command line always sits between a "{HARD_R}" and a "{HARD_L}" -- it shows
#   even when every status segment is empty. No colour-matched triangles
#   between segments: that needs each to know its neighbours, which Starship
#   can't express for segments that appear/disappear on their own. Order L->R:
#     cmd_duration  node/go/rust/python  aws  kubernetes  git-state
#     exit-code  branch + status + line-metrics
#
# GLYPHS are Nerd Font PUA chars; they render only if the terminal font
# resolves to a real Nerd Font by the EXACT name it exposes -- for Ghostty
# here that is "JetBrainsMono Nerd Font Mono" (see the Ghostty config).
# Check:  printf 'br {BRANCH}  clk {CLOCK}  node {NODE}  go {GO}  rs {RUST}  py {PY}  aws {AWS}\\n'

add_newline = false

format = """
[$hostname$username]({L_HOST})\\
[{HARD_R}](fg:#434C5E bg:#5E81AC)\\
[$directory$jobs]({L_DIR})\\
[{HARD_R}](bold fg:#5E81AC) """

right_format = """[{HARD_L}](bold fg:{BAR})\\
$cmd_duration$nodejs$golang$rust$python$aws$kubernetes$git_state$status$git_branch$git_status$git_metrics"""

# ================================================================= LEFT ====

[hostname]
ssh_only = false
disabled = false
format = "[ $hostname {CHEV_R}]($style)"
style = "{L_HOST}"

[username]
show_always = true
disabled = false
format = "[ $user ]($style)"
style_user = "{L_HOST}"
style_root = "{L_HOST}"

[directory]
disabled = false
format = "[ $path]($style)[$read_only]($read_only_style)"
style = "{L_DIR}"
truncation_length = 3
truncation_symbol = "…/"

[jobs]
number_threshold = 1
symbol_threshold = 1
format = "[ {CHEV_R} $symbol$number ]($style)"
style = "{L_DIR}"
symbol = "✦"

# ================================================================ RIGHT ====
# All segments on bg:{BAR}; only the fg colour and icon change per segment.

[cmd_duration]
min_time = 2000
show_milliseconds = false
format = "[ {CLOCK} $duration ]($style)"
style = "fg:#AEB9CC bg:{BAR}"

[nodejs]
format = "[ {NODE} $version ]($style)"
version_format = "v${{raw}}"
style = "fg:#8CE05A bg:{BAR}"

[golang]
format = "[ {GO} $version ]($style)"
version_format = "v${{raw}}"
style = "fg:#63D4EC bg:{BAR}"

[rust]
format = "[ {RUST} $version ]($style)"
version_format = "v${{raw}}"
style = "fg:#F0925A bg:{BAR}"

[python]
format = "[ {PY} $version( $virtualenv) ]($style)"
symbol = ""
version_format = "v${{raw}}"
style = "fg:#F5D24E bg:{BAR}"

[aws]
format = "[ {AWS} $profile( $region) ]($style)"
style = "fg:#F2A65A bg:{BAR}"

[kubernetes]
disabled = false
detect_files = ['Chart.yaml', 'skaffold.yaml', 'kustomization.yaml']
detect_folders = ['k8s', 'manifests', 'kubernetes', '.helm']
format = "[ {KUBE} $context( $namespace) ]($style)"
style = "fg:#63D4EC bg:{BAR}"

[git_state]
format = "[ $state( $progress_current/$progress_total) ]($style)"
style = "fg:#DDA9E4 bg:{BAR} bold"

[status]
disabled = false
pipestatus = true
format = "[ {FAIL} $status ]($style)"
pipestatus_format = "[ {FAIL} $pipestatus=>$status ]($style)"
style = "fg:#F26D75 bg:{BAR} bold"

[git_branch]
format = "[ {BRANCH} $branch ]($style)"
style = "fg:#A9E080 bg:{BAR} bold"

[git_status]
# Continues straight after the branch (branch supplied the leading space).
format = "([$all_status$ahead_behind ]($style))"
style = "fg:#D8DEE9 bg:{BAR}"
conflicted = "✖${{count}}"
ahead = "↑${{count}}"
behind = "↓${{count}}"
diverged = "↑${{ahead_count}}↓${{behind_count}}"
staged = "●${{count}}"
modified = "✚${{count}}"
untracked = "…${{count}}"
stashed = "⚑${{count}}"

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"
added_style = "fg:#8CE05A bg:{BAR}"
deleted_style = "fg:#F26D75 bg:{BAR}"
'''

out = os.path.expanduser("~/.config/starship.toml")
with open(out, "w", encoding="utf-8") as f:
    f.write(TOML)
pua = sum(1 for c in TOML if 0xE000 <= ord(c) <= 0xF8FF)
print(f"wrote {out}  ({len(TOML)} bytes, {pua} PUA glyphs)")
